batch_size: [32, 101, 512, 800]                  # batch size
epochs: 1                     # total number of epochs
eval_every_n_epochs: 1          # validation frequency in ./ckpt
log_every_n_steps: 50           # print training log frequency
fine_tune_from: gin_concat_R1000_E8000  # sub directory of pre-trained model in ./ckpt
fp16_precision: False           # float precision 16 (i.e. True/False)
init_lr: [0.0005, 0.001]                 # initial learning rate for the prediction head
init_base_lr: [0.00005, 0.0001, 0.0002, 0.0005]            # initial learning rate for the base GNN encoder
weight_decay: 1e-6              # weight decay of Adam
gpu: cuda:0                     # training GPU
task_name: BBBP                  # name of fine-tuning benchmark, inlcuding
                                # classifications: BBBP/BACE/ClinTox/Tox21/HIV/SIDER/MUV
                                # regressions: FreeSolv/ESOL/Lipo/qm7/qm8/qm9

model_type: gin_concat                 # GNN backbone (i.e., gin/gcn)
model: 
  num_layer: 5                          # number of graph conv layers
  emb_dim: 200                          # embedding dimension in graph conv layers
  feat_dim: 8000                         # output feature dimention
  pool: add                            # readout pooling (i.e., mean/max/add)
  drop_ratio: [0, 0.1, 0.3, 0.5]
  pred_n_layer: [1, 2]
  pred_act: ["softplus", "relu"]

dataset:
  num_workers: 10                # dataloader number of workers
  valid_size: 0.1               # ratio of validation data
  test_size: 0.1                # ratio of test data
  splitting: scaffold           # data splitting (i.e., random/scaffold)

random_search:
  n_models: 1
  n_trains: 1