batch_size: [32, 101, 512, 800]                  # Possible batch sizes
epochs: 100                     # total number of epochs
eval_every_n_epochs: 1          # validation frequency in ./ckpt
log_every_n_steps: 50           # print training log frequency
fine_tune_from: gin_concat_R1000_E8000_lambda0.0001  # sub directory of pre-trained model in ./ckpt
init_lr: [0.0005, 0.001]                 # Possible initial learning rate for the prediction head
init_base_lr: [0.00005, 0.0001, 0.0002, 0.0005]            # Possible initial learning rate for the base GNN encoder
weight_decay: 0.000001              # weight decay of Adam
gpu: cuda:0                     # training device
task_name: BBBP                  # name of fine-tuning benchmark, inlcuding
                                # classifications: BBBP/BACE/ClinTox/Tox21/HIV/SIDER/MUV
                                # regressions: FreeSolv/ESOL/Lipo/qm7/qm8/qm9
model_outdir: finetune            # output directory of fine-tuned models
experiment_outdir: experiments
model: 
  drop_ratio: [0, 0.1, 0.3, 0.5]       # Possible dropout ratios
  pred_n_layer: [1, 2]                 # Possible number of layers on prediction head
  pred_act: ["softplus", "relu"]       # Possible activation functions on prediction head

dataset:
  num_workers: 10                # dataloader number of workers
  valid_size: 0.1               # ratio of validation data
  test_size: 0.1                # ratio of test data
  splitting: scaffold           # data splitting (i.e., random/scaffold)

random_search:
  n_models: 5                  # Number of hyperparameter configurations to try
  n_trains: 3                  # Number of training runs for each hyperparameter configuration